# Generated by Django 5.2.5 on 2025-08-18 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=400)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('geocoded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requester', models.CharField(blank=True, max_length=150)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='weather.location')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('temp_f', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.location')),
                ('source_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weatherquery')),
            ],
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['start_date', 'end_date'], name='weather_wea_start_d_19cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherrecord',
            index=models.Index(fields=['location', 'date'], name='weather_wea_locatio_738a21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherrecord',
            unique_together={('location', 'date')},
        ),
    ]
